import { Vehicle, DealerBid } from "./types";

export const MOCK_VEHICLES: Vehicle[] = [
  // --- SAN FRANCISCO / BAY AREA ---
  {
    id: "v1",
    vin: "WBA33AY08RF892110",
    year: 2026,
    make: "BMW",
    model: "3 Series",
    trim: "330i M Sport",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-4 (255 hp)",
    drivetrain: "RWD",
    transmission: "Automatic",
    exteriorColor: "Mineral Grey Metallic",
    interiorColor: "Tacora Red Perforated Sensatec",
    msrp: 54200,
    dealerPrice: 51200,
    daysOnLot: 34,
    status: "on_lot",
    location: {
      dealerName: "BMW of San Rafael",
      city: "San Rafael",
      state: "CA",
      distanceMiles: 14,
    },
    packages: [
      "M Sport Package",
      "Shadowline Package",
      "Premium Package (Heated Seats + HUD)",
      "19\" M Double-Spoke Jet Black Wheels",
      "Harman Kardon Surround Sound"
    ],
    options: [
      { code: "ZMP", name: "M Sport Package", price: 2550, category: "package" },
      { code: "ZPL", name: "Shadowline Package", price: 650, category: "package" },
      { code: "ZPP", name: "Premium Package", price: 1900, category: "package" },
      { code: "688", name: "Harman Kardon Surround Sound", price: 875, category: "standalone" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    mileage: 8,
    dealerUrl: "https://www.bmwsanrafael.com/new/BMW/2026-BMW-330i-M-Sport-wba33ay08rf892110.htm",
  },
  {
    id: "v2",
    vin: "WBA33AY05RF774102",
    year: 2026,
    make: "BMW",
    model: "3 Series",
    trim: "330i xDrive",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-4 (255 hp)",
    drivetrain: "AWD",
    transmission: "Automatic",
    exteriorColor: "Black Sapphire Metallic",
    interiorColor: "Black Perforated Sensatec",
    msrp: 55900,
    dealerPrice: 53500,
    daysOnLot: 19,
    status: "on_lot",
    location: {
      dealerName: "Stevens Creek BMW",
      city: "Santa Clara",
      state: "CA",
      distanceMiles: 38,
    },
    packages: [
      "Premium Package (Heated Seats + HUD)",
      "Driving Assistance Professional",
      "Parking Assistance Package"
    ],
    options: [
      { code: "ZPP", name: "Premium Package", price: 1900, category: "package" },
      { code: "ZDY", name: "Driving Assistance Pro", price: 1700, category: "package" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80",
    mileage: 12,
    dealerUrl: "https://www.stevenscreekbmw.com/new/BMW/2026-BMW-330i-xDrive-wba33ay05rf774102.htm",
  },
  {
    id: "v3",
    vin: "WP0AB2A99SS109284",
    year: 2026,
    make: "Porsche",
    model: "911",
    trim: "Carrera S",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo Flat-6 (443 hp)",
    drivetrain: "RWD",
    transmission: "Manual",
    exteriorColor: "Gentian Blue Metallic",
    interiorColor: "Black / Mojave Beige Leather",
    msrp: 142800,
    dealerPrice: 142800,
    daysOnLot: 42,
    status: "on_lot",
    location: {
      dealerName: "Porsche Redwood City",
      city: "Redwood City",
      state: "CA",
      distanceMiles: 24,
    },
    packages: [
      "Sport Chrono Package",
      "Sport Exhaust System",
      "PASM Sport Suspension (-10mm)",
      "20\"/21\" Carrera Classic Wheels"
    ],
    options: [
      { code: "8LH", name: "Sport Chrono Package", price: 2790, category: "package" },
      { code: "0P8", name: "Sport Exhaust System", price: 2950, category: "standalone" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    mileage: 18,
    dealerUrl: "https://www.porscheredwoodcity.com/inventory/new-2026-porsche-911-carrera-s-wp0ab2a99ss109284/",
  },
  {
    id: "v4",
    vin: "JTDKA3FP5R0092182",
    year: 2026,
    make: "Toyota",
    model: "Prius",
    trim: "Limited AWD",
    bodyType: "Hatchback",
    engine: "2.0L Hybrid (196 hp)",
    drivetrain: "AWD",
    transmission: "Automatic",
    exteriorColor: "Wind Chill Pearl",
    interiorColor: "Gradient Black SofTex",
    msrp: 38450,
    dealerPrice: 38450,
    daysOnLot: 4,
    status: "in_transit",
    location: {
      dealerName: "Toyota of Berkeley",
      city: "Berkeley",
      state: "CA",
      distanceMiles: 11,
    },
    packages: [
      "Solar Roof Package",
      "Digital Rearview Mirror",
      "Advanced Park Assist"
    ],
    options: [
      { code: "SR", name: "Solar Roof Package", price: 610, category: "exterior" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80",
    mileage: 0,
    dealerUrl: "https://www.toyotaofberkeley.com/new-inventory/2026-toyota-prius-limited-awd-jtdka3fp5r0092182.htm",
  },
  {
    id: "v5",
    vin: "1GYKPDR49RZ110948",
    year: 2026,
    make: "Cadillac",
    model: "Lyriq",
    trim: "Luxury 1 AWD",
    bodyType: "SUV",
    engine: "Dual Motor Electric (500 hp)",
    drivetrain: "AWD",
    transmission: "Automatic",
    exteriorColor: "Stellar Black Metallic",
    interiorColor: "Noir with Santorini Blue Accents",
    msrp: 64200,
    dealerPrice: 58900,
    daysOnLot: 61,
    status: "on_lot",
    location: {
      dealerName: "Cadillac Marin",
      city: "Corte Madera",
      state: "CA",
      distanceMiles: 16,
    },
    packages: [
      "Super Cruise Driver Assistance",
      "AKG Studio 19-Speaker Audio",
      "Panoramic Power Opening Sunroof"
    ],
    options: [
      { code: "UKL", name: "Super Cruise Package", price: 2500, category: "package" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
    mileage: 45,
    dealerUrl: "https://www.cadillacmarin.com/VehicleDetails/new-2026-Cadillac-LYRIQ-1GYKPDR49RZ110948",
  },

  // --- NEW YORK / TRI-STATE DEALERSHIPS ---
  {
    id: "v6",
    vin: "WBA33AY02RF119284",
    year: 2026,
    make: "BMW",
    model: "3 Series",
    trim: "330i xDrive M Sport",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-4 (255 hp)",
    drivetrain: "AWD",
    transmission: "Automatic",
    exteriorColor: "Portimao Blue Metallic",
    interiorColor: "Oyster Vernasca Leather",
    msrp: 56400,
    dealerPrice: 52800,
    daysOnLot: 21,
    status: "on_lot",
    location: {
      dealerName: "BMW of Manhattan",
      city: "New York",
      state: "NY",
      distanceMiles: 8,
    },
    packages: [
      "M Sport Package",
      "Shadowline Package",
      "Executive Package (Harman Kardon + Laserlights)"
    ],
    options: [
      { code: "ZMP", name: "M Sport Package", price: 2550, category: "package" },
      { code: "ZPL", name: "Shadowline Package", price: 650, category: "package" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    mileage: 15,
    dealerUrl: "https://www.bmwofmanhattan.com/new/BMW/2026-BMW-330i-xDrive-wba33ay02rf119284.htm",
  },
  {
    id: "v7",
    vin: "WP0AB2A97SS491820",
    year: 2026,
    make: "Porsche",
    model: "911",
    trim: "Carrera 4 GTS",
    bodyType: "Coupe",
    engine: "3.6L T-Hybrid Boxer-6 (532 hp)",
    drivetrain: "AWD",
    transmission: "Dual-Clutch",
    exteriorColor: "Carmine Red",
    interiorColor: "GTS Interior Package in Carmine Red",
    msrp: 172900,
    dealerPrice: 172900,
    daysOnLot: 11,
    status: "in_transit",
    location: {
      dealerName: "Porsche Brooklyn",
      city: "Brooklyn",
      state: "NY",
      distanceMiles: 12,
    },
    packages: [
      "Sport Chrono Package",
      "Sport Exhaust with Black Tailpipes",
      "Front Axle Lift System",
      "Burmester 3D Surround Sound"
    ],
    options: [
      { code: "8LH", name: "Sport Chrono Package", price: 2790, category: "package" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
    mileage: 0,
    dealerUrl: "https://www.porschebrooklyn.com/inventory/new-2026-porsche-911-carrera-4-gts-wp0ab2a97ss491820/",
  },

  // --- TEXAS / DALLAS DEALERSHIPS ---
  {
    id: "v8",
    vin: "1FA6P8CF9R5102941",
    year: 2026,
    make: "Ford",
    model: "Mustang",
    trim: "Dark Horse",
    bodyType: "Coupe",
    engine: "5.0L Coyote V8 (500 hp)",
    drivetrain: "RWD",
    transmission: "Manual",
    exteriorColor: "Vapor Blue Metallic",
    interiorColor: "Deep Indigo Leather",
    msrp: 62800,
    dealerPrice: 62800,
    daysOnLot: 28,
    status: "on_lot",
    location: {
      dealerName: "Park Cities Ford Dallas",
      city: "Dallas",
      state: "TX",
      distanceMiles: 10,
    },
    packages: [
      "Handling Package (MagneRide + Rear Spoiler)",
      "Brembo 6-Piston Performance Brakes",
      "B&O 12-Speaker Sound System"
    ],
    options: [
      { code: "67J", name: "Dark Horse Handling Package", price: 4995, category: "package" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80",
    mileage: 22,
    dealerUrl: "https://www.parkcitiesforddallas.com/new/Ford/2026-Ford-Mustang-Dark-Horse-1fa6p8cf9r5102941.htm",
  },
  {
    id: "v9",
    vin: "JTDKA3FP8R0044192",
    year: 2026,
    make: "Toyota",
    model: "Prius",
    trim: "XLE AWD",
    bodyType: "Hatchback",
    engine: "2.0L Hybrid (196 hp)",
    drivetrain: "AWD",
    transmission: "Automatic",
    exteriorColor: "Guardian Gray",
    interiorColor: "Black SofTex",
    msrp: 34100,
    dealerPrice: 33400,
    daysOnLot: 15,
    status: "on_lot",
    location: {
      dealerName: "Toyota of Dallas",
      city: "Dallas",
      state: "TX",
      distanceMiles: 14,
    },
    packages: [
      "12.3-inch Multimedia Display",
      "Fixed Glass Roof",
      "Wireless Smartphone Charging"
    ],
    options: [
      { code: "NV", name: "12.3-inch Display Audio", price: 735, category: "standalone" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=80",
    mileage: 14,
    dealerUrl: "https://www.toyotaofdallas.com/new-inventory/2026-toyota-prius-xle-awd-jtdka3fp8r0044192.htm",
  },

  // --- LOS ANGELES / SOCAL DEALERSHIPS ---
  {
    id: "v10",
    vin: "5YJ3E1EB8RF901824",
    year: 2026,
    make: "Tesla",
    model: "Model 3",
    trim: "Performance AWD",
    bodyType: "Sedan",
    engine: "Dual Motor All-Wheel Drive (510 hp)",
    drivetrain: "AWD",
    transmission: "Automatic",
    exteriorColor: "Ultra Red",
    interiorColor: "Black and White Premium Interior",
    msrp: 54990,
    dealerPrice: 54990,
    daysOnLot: 6,
    status: "in_transit",
    location: {
      dealerName: "Tesla Century City",
      city: "Los Angeles",
      state: "CA",
      distanceMiles: 8,
    },
    packages: [
      "Adaptive Damping Suspension",
      "Track Mode V3",
      "20\" Warp Wheels",
      "Carbon Fiber Spoiler"
    ],
    options: [
      { code: "PR01", name: "Ultra Red Paint", price: 2000, category: "exterior" }
    ],
    imageUrl: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
    mileage: 0,
    dealerUrl: "https://www.tesla.com/model3/design#overview",
  }
];

export const MOCK_POPULAR_PACKAGES = [
  { name: "M Sport Package", count: 18, category: "Performance" },
  { name: "Shadowline Package", count: 24, category: "Aesthetic" },
  { name: "Premium Package", count: 31, category: "Comfort" },
  { name: "Sport Chrono", count: 9, category: "Performance" },
  { name: "Driving Assistance Pro", count: 14, category: "Tech" },
  { name: "Harman Kardon Audio", count: 22, category: "Audio" },
  { name: "Super Cruise", count: 8, category: "Tech" },
  { name: "Solar Roof", count: 6, category: "Eco" },
  { name: "Handling Package", count: 5, category: "Performance" }
];

export const INITIAL_DEMO_BIDS: DealerBid[] = [
  {
    id: "bid-1",
    dealRequestId: "req-demo-1",
    dealerName: "BMW of San Rafael",
    dealerCity: "San Rafael",
    dealerState: "CA",
    distanceMiles: 14,
    matchedVin: "WBA33AY08RF892110",
    matchedVehicleTitle: "2026 BMW 330i M Sport",
    matchedVehicleSpec: "Mineral Grey • Shadowline • Premium Pkg • 19\" Wheels",
    matchedVehicleImageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    vehicleStatus: "on_lot",
    msrp: 54200,
    dealerDiscountDollars: 4607,
    dealerDiscountPercent: 8.5,
    manufacturerRebates: 1000,
    sellingPrice: 48593,
    salesTax: 4191,
    dmvFees: 754,
    docFee: 85,
    dealerAccessories: 0,
    totalOtdPrice: 53623,
    financeMonthlyEstimate: 815,
    leaseMonthlyEstimate: 589,
    notes: "Unit is on lot, ready for same-day delivery. Full MSRP discount applied with $0 dealer add-ons.",
    rank: 1,
    createdAt: "2 mins ago",
    isTopDeal: true,
    salesRep: {
      name: "Marcus Vance",
      title: "Internet Sales Director",
      phone: "(415) 555-0199",
    },
  },
  {
    id: "bid-2",
    dealRequestId: "req-demo-1",
    dealerName: "Peter Pan BMW",
    dealerCity: "San Mateo",
    dealerState: "CA",
    distanceMiles: 19,
    matchedVin: "WBA33AY09RF611293",
    matchedVehicleTitle: "2026 BMW 330i M Sport",
    matchedVehicleSpec: "Brooklyn Grey • Premium Pkg • Harman Kardon",
    matchedVehicleImageUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    vehicleStatus: "in_transit",
    msrp: 53800,
    dealerDiscountDollars: 3874,
    dealerDiscountPercent: 7.2,
    manufacturerRebates: 1000,
    sellingPrice: 48926,
    salesTax: 4220,
    dmvFees: 758,
    docFee: 85,
    dealerAccessories: 0,
    totalOtdPrice: 53989,
    financeMonthlyEstimate: 835,
    leaseMonthlyEstimate: 615,
    notes: "Arriving in 6 days. Can lock in allocation at 7.2% off MSRP today.",
    rank: 2,
    createdAt: "14 mins ago",
    salesRep: {
      name: "Elena Rostova",
      title: "Client Advisor",
      phone: "(650) 555-0142",
    },
  }
];

export const SAMPLE_TRADE_IN_VEHICLE = {
  hasTradeIn: true,
  year: 2022,
  make: "Audi",
  model: "A4",
  trim: "45 TFSI Quattro Premium Plus",
  mileage: 28450,
  vin: "WAUZZAF42NA091482",
  condition: "very_good" as const,
  estimatedValueMin: 24500,
  estimatedValueMax: 26800,
  loanBalance: 8200,
  photos: [
    {
      id: "tp-1",
      angle: "front_angle" as const,
      label: "Front 3/4 Exterior",
      imageUrl: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "tp-2",
      angle: "rear_angle" as const,
      label: "Rear 3/4 Exterior",
      imageUrl: "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "tp-3",
      angle: "interior_odometer" as const,
      label: "Dashboard & Odometer (28,450 mi)",
      imageUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "tp-4",
      angle: "tires_wheels" as const,
      label: "Tires & Alloy Wheels",
      imageUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    },
  ],
};

export const DEMO_BUYER_USER: import("./types").UserProfile = {
  id: "user-buyer-101",
  name: "Alex Rivera",
  email: "alex.rivera@example.com",
  role: "buyer",
  phone: "(415) 555-8910",
  zipCode: "94107",
  buyerAlias: "Buyer #CA-4921",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
  savedVehicleIds: ["veh-1", "veh-4"],
};

export const DEMO_DEALER_USER: import("./types").UserProfile = {
  id: "user-dealer-202",
  name: "Marcus Vance",
  email: "marcus.vance@bmwsanrafael.com",
  role: "dealer",
  phone: "(415) 555-0199",
  zipCode: "94901",
  dealerName: "BMW of San Rafael",
  avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
  savedVehicleIds: [],
};

