// Curated NJ single-franchise authorized rooftops for in-scope brands.
// Excludes OUT brands, Open Road / AutoNation / used superstores, and
// obvious multi-franchise lots. Domains are the public dealer host; the
// bot-protection report will classify whatever a normal HTTP client sees.

function rows(make, list) {
  return list.map((d) => ({ ...d, make, state: 'NJ' }));
}

export const NJ_DEALER_SEED = [
  ...rows('Porsche', [
    { id: 'jack-daniels-porsche', name: 'Jack Daniels Porsche', city: 'Upper Saddle River', domain: 'jackdaniels.porsche.com' },
    { id: 'paul-miller-porsche', name: 'Paul Miller Porsche', city: 'Parsippany', domain: 'paulmillerporsche.com' },
    { id: 'porsche-englewood', name: 'Porsche Englewood', city: 'Englewood', domain: 'porscheenglewood.com' },
    { id: 'porsche-monmouth', name: 'Porsche Monmouth', city: 'West Long Branch', domain: 'porschemonmouth.com' },
    { id: 'porsche-cherry-hill', name: 'Porsche Cherry Hill', city: 'Cherry Hill', domain: 'porschecherryhill.com' },
    { id: 'ray-catena-porsche', name: 'Ray Catena Porsche', city: 'Edison', domain: 'raycatenaporsche.com' },
    { id: 'porsche-princeton', name: 'Porsche Princeton', city: 'Lawrenceville', domain: 'princetonporsche.com' },
    { id: 'porsche-bridgewater', name: 'Porsche Bridgewater', city: 'Bridgewater', domain: 'porschebridgewater.com' },
    { id: 'porsche-millburn', name: 'Porsche Millburn', city: 'Millburn', domain: 'porschemillburn.com' },
    { id: 'porsche-flemington', name: 'Porsche Flemington', city: 'Flemington', domain: 'porscheflemington.com' },
  ]),
  ...rows('Acura', [
    { name: 'Park Ave. Acura', city: 'Rochelle Park', domain: 'parkaveacura.com' },
    { name: 'DCH Montclair Acura', city: 'Verona', domain: 'dchmontclairacura.com' },
    { name: 'Springfield Acura', city: 'Springfield', domain: 'springfieldacura.com' },
    { name: 'Acura of Ramsey', city: 'Ramsey', domain: 'ramseyacura.com' },
    { name: 'Autosport Acura of Denville', city: 'Denville', domain: 'acuraofdenville.com' },
    { name: "Bill Vince's Bridgewater Acura", city: 'Bridgewater', domain: 'bridgewateracura.com' },
    { name: 'Acura of Ocean', city: 'Ocean', domain: 'acuraofocean.com' },
    { name: 'Clinton Acura', city: 'Clinton', domain: 'clintonacura.com' },
    { name: 'Precision Acura of Princeton', city: 'Lawrenceville', domain: 'precisionacura.com' },
    { name: 'Elite Acura', city: 'Maple Shade', domain: 'eliteacura.com' },
    { name: 'Acura Turnersville', city: 'Turnersville', domain: 'acuraturnersville.com' },
    { name: 'Key Acura of Atlantic City', city: 'Egg Harbor Township', domain: 'keyacuraofatlanticcity.com' },
  ]),
  ...rows('Toyota', [
    { name: 'Sansone Toyota', city: 'Avenel', domain: '66toyota.com' },
    { name: 'Liberty Toyota', city: 'Burlington', domain: 'libertytoyota.com' },
    { name: 'Toyota World of Clinton', city: 'Clinton', domain: 'toyotaworldclinton.com' },
    { name: 'Dayton Toyota', city: 'Dayton', domain: 'daytontoyota.com' },
    { name: 'Galaxy Toyota', city: 'Eatontown', domain: 'galaxytoyota.net' },
    { name: 'Parkway Toyota', city: 'Englewood Cliffs', domain: 'parkwaytoyota.com' },
    { name: 'Glen Motors', city: 'Fair Lawn', domain: 'glenmotors.com' },
    { name: 'Fred Beans Toyota of Flemington', city: 'Flemington', domain: 'fredbeanstoyotaofflemington.com' },
    { name: 'DCH Freehold Toyota', city: 'Freehold', domain: 'dchfreeholdtoyota.com' },
    { name: 'Empire Toyota of Green Brook', city: 'Green Brook', domain: 'empiretoyotaofgreenbrook.com' },
    { name: 'Toyota of Hackensack', city: 'Hackensack', domain: 'toyotaofhackensack.com' },
    { name: 'Route 22 Toyota', city: 'Hillside', domain: 'route22toyota.com' },
    { name: 'Hudson Toyota', city: 'Jersey City', domain: 'hudsontoyota.com' },
    { name: 'Toyota World of Lakewood', city: 'Lakewood', domain: 'toyotaworldlakewood.com' },
    { name: 'Team Toyota of Princeton', city: 'Lawrenceville', domain: 'teamtoyotaofprinceton.com' },
    { name: 'Towne Toyota', city: 'Ledgewood', domain: 'townetoyota.com' },
    { name: 'Toyota Universe', city: 'Little Falls', domain: 'toyotauniverse.com' },
    { name: 'Shore Toyota', city: 'Mays Landing', domain: 'shoretoyota.com' },
    { name: 'Toyota of Morristown', city: 'Morristown', domain: 'toyotaofmorristown.com' },
    { name: 'Holman Toyota', city: 'Mount Laurel', domain: 'holmantoyota.com' },
    { name: 'Toyota World of Newton', city: 'Newton', domain: 'toyotaworldnewton.com' },
    { name: 'DCH Brunswick Toyota', city: 'North Brunswick', domain: 'dchbrunswicktoyota.com' },
    { name: 'Crestmont Toyota', city: 'Pompton Plains', domain: 'crestmonttoyota.com' },
    { name: 'Prestige Toyota of Ramsey', city: 'Ramsey', domain: 'prestigestoyota.com' },
    { name: 'Toyota of Runnemede', city: 'Runnemede', domain: 'toyotaofrunnemede.com' },
    { name: 'Autoland Toyota', city: 'Springfield', domain: 'autolandtoyota.com' },
    { name: 'Gateway Toyota', city: 'Toms River', domain: 'gatewaytoyota.com' },
    { name: 'Toyota of Turnersville', city: 'Turnersville', domain: 'toyotaofturnersville.com' },
    { name: 'Toyota of Vineland', city: 'Vineland', domain: 'toyotaofvineland.com' },
    { name: 'Paul Miller Toyota of West Caldwell', city: 'West Caldwell', domain: 'paulmillertoyota.com' },
    { name: 'East Coast Toyota', city: 'Wood-Ridge', domain: 'eastcoasttoyota.com' },
  ]),
  ...rows('Lexus', [
    { name: 'Lexus of Bridgewater', city: 'Bridgewater', domain: 'lexusofbridgewater.com' },
    { name: 'Lexus of Englewood', city: 'Englewood', domain: 'lexusofenglewood.com' },
    { name: 'Lexus of Edison', city: 'Edison', domain: 'lexusofedison.com' },
    { name: 'Lexus of Route 17', city: 'Saddle Brook', domain: 'lexusofroute17.com' },
    { name: 'Lexus of Route 23', city: 'Butler', domain: 'lexusofroute23.com' },
    { name: 'Ray Catena Lexus', city: 'Edison', domain: 'raycatenalexus.com' },
    { name: 'Lexus of Atlantic City', city: 'Egg Harbor Township', domain: 'lexusofatlanticcity.com' },
    { name: 'Lexus of Cherry Hill', city: 'Maple Shade', domain: 'lexusofcherryhill.com' },
    { name: 'Prestige Lexus of Ramsey', city: 'Ramsey', domain: 'prestigelexus.com' },
    { name: 'DCH Lexus of Tenafly', city: 'Tenafly', domain: 'dchlexusoftenafly.com' },
    { name: 'Lexus of Freehold', city: 'Freehold', domain: 'lexusoffreehold.com' },
    { name: 'Holman Lexus of Maple Shade', city: 'Maple Shade', domain: 'holmanlexus.com' },
  ]),
  ...rows('Honda', [
    { name: 'Honda of Turnersville', city: 'Turnersville', domain: 'hondaturnersville.com' },
    { name: 'Honda of Princeton', city: 'Princeton', domain: 'hondaofprinceton.com' },
    { name: 'DCH Kay Honda', city: 'Eatontown', domain: 'dchkayhonda.com' },
    { name: 'DCH Brunswick Honda', city: 'North Brunswick', domain: 'dchbrunswickhonda.com' },
    { name: 'Honda of Freehold', city: 'Freehold', domain: 'hondaoffreehold.com' },
    { name: 'Honda of Watchung', city: 'Watchung', domain: 'hondaofwatchung.com' },
    { name: 'World Honda', city: 'Wanaque', domain: 'worldhondanewjersey.com' },
    { name: 'Honda of Toms River', city: 'Toms River', domain: 'hondaoftomsriver.com' },
    { name: 'Honda of Atlantic City', city: 'Egg Harbor Township', domain: 'hondaofatlanticcity.com' },
    { name: 'Honda of Burlingame', city: 'Burlington', domain: 'hondaofburlington.com' },
    { name: 'Route 22 Honda', city: 'Hillside', domain: 'route22honda.com' },
    { name: 'Honda of Bridgewater', city: 'Bridgewater', domain: 'hondaofbridgewater.com' },
    { name: 'Honda Universe', city: 'Little Falls', domain: 'hondauniverse.com' },
    { name: 'Paul Miller Honda', city: 'Parsippany', domain: 'paulmillerhonda.com' },
    { name: 'Honda of Princeton Junction', city: 'Lawrenceville', domain: 'hondalawrenceville.com' },
    { name: 'Garden State Honda', city: 'Clifton', domain: 'gardenstatehonda.com' },
    { name: 'Honda of Morristown', city: 'Morristown', domain: 'hondaofmorristown.com' },
    { name: 'Quality Honda', city: 'Englewood', domain: 'qualityhondanj.com' },
    { name: 'Mancini Honda', city: 'New Brunswick', domain: 'mancinihonda.com' },
  ]),
  ...rows('Kia', [
    { name: 'Kia of North Brunswick', city: 'North Brunswick', domain: 'kiaofnorthbrunswick.com' },
    { name: 'Kia of Hackensack', city: 'Hackensack', domain: 'kiaofhackensack.com' },
    { name: 'Kia of Englewood', city: 'Englewood', domain: 'kiaofenglewood.com' },
    { name: 'Freehold Kia', city: 'Freehold', domain: 'freeholdkia.com' },
    { name: 'Kia of Atlantic City', city: 'Egg Harbor Township', domain: 'kiaofatlanticcity.com' },
    { name: 'Turnersville Kia', city: 'Turnersville', domain: 'turnersvillekia.com' },
    { name: 'Flemington Kia', city: 'Flemington', domain: 'flemingtonkia.com' },
    { name: 'Kia of Morristown', city: 'Morristown', domain: 'kiaofmorristown.com' },
    { name: 'Route 46 Kia', city: 'Little Falls', domain: 'route46kia.com' },
    { name: 'Kia of Cherry Hill', city: 'Cherry Hill', domain: 'kiaofcherryhill.com' },
    { name: 'Kia of Toms River', city: 'Toms River', domain: 'kiaoftomsriver.com' },
    { name: 'Hudson Kia', city: 'Jersey City', domain: 'hudsonkia.com' },
  ]),
  ...rows('Nissan', [
    { name: 'Nissan of Turnersville', city: 'Turnersville', domain: 'nissanofturnersville.com' },
    { name: 'Nissan of Atlantic City', city: 'Egg Harbor Township', domain: 'nissanofatlanticcity.com' },
    { name: 'Freehold Nissan', city: 'Freehold', domain: 'freeholdnissan.com' },
    { name: 'Nissan of Eatontown', city: 'Eatontown', domain: 'nissanofeatontown.com' },
    { name: 'Route 22 Nissan', city: 'Hillside', domain: 'route22nissan.com' },
    { name: 'Nissan of Englewood', city: 'Englewood', domain: 'nissanofenglewood.com' },
    { name: 'Hudson Nissan', city: 'Jersey City', domain: 'hudsonnissan.com' },
    { name: 'Nissan of Somerville', city: 'Somerville', domain: 'nissanofsomerville.com' },
    { name: 'Flemington Nissan', city: 'Flemington', domain: 'flemingtonnissan.com' },
    { name: 'Nissan of Cherry Hill', city: 'Cherry Hill', domain: 'nissanofcherryhill.com' },
    { name: 'DCH Millburn Nissan', city: 'Maplewood', domain: 'dchmillburnnissan.com' },
    { name: 'Nissan of Morristown', city: 'Morristown', domain: 'nissanofmorristown.com' },
  ]),
  ...rows('Infiniti', [
    { name: 'Infiniti of Englewood', city: 'Englewood', domain: 'infinitiofenglewood.com' },
    { name: 'Infiniti of Edison', city: 'Edison', domain: 'infinitiofedison.com' },
    { name: 'Infiniti of Bridgewater', city: 'Bridgewater', domain: 'infinitiofbridgewater.com' },
    { name: 'Infiniti of Atlantic City', city: 'Egg Harbor Township', domain: 'infinitiofatlanticcity.com' },
    { name: 'Infiniti of Turnersville', city: 'Turnersville', domain: 'infinitiofturnersville.com' },
    { name: 'DCH Millburn Infiniti', city: 'Maplewood', domain: 'dchmillburninfiniti.com' },
    { name: 'Ray Catena Infiniti', city: 'Edison', domain: 'raycatenainfiniti.com' },
    { name: 'Flemington Infiniti', city: 'Flemington', domain: 'flemingtoninfiniti.com' },
  ]),
  ...rows('Subaru', [
    { name: 'Subaru of Morristown', city: 'Morristown', domain: 'subaruofmorristown.com' },
    { name: 'Subaru of Englewood', city: 'Englewood', domain: 'subaruofenglewood.com' },
    { name: 'Subaru of Cherry Hill', city: 'Cherry Hill', domain: 'subaruofcherryhill.com' },
    { name: 'Turnersville Subaru', city: 'Turnersville', domain: 'turnersvillesubaru.com' },
    { name: 'Flemington Subaru', city: 'Flemington', domain: 'flemingtonsubaru.com' },
    { name: 'Subaru of Ramsey', city: 'Ramsey', domain: 'subaruoframsey.com' },
    { name: 'Hudson Subaru', city: 'Jersey City', domain: 'hudsonsubaru.com' },
    { name: 'Liberty Subaru', city: 'Emerson', domain: 'libertysubaru.com' },
    { name: 'Subaru of Somerset', city: 'Somerset', domain: 'subaruofsomerset.com' },
    { name: 'Toms River Subaru', city: 'Toms River', domain: 'tomsriversubaru.com' },
    { name: 'Subaru of Atlantic City', city: 'Egg Harbor Township', domain: 'subaruofatlanticcity.com' },
    { name: 'Prestige Subaru', city: 'Ramsey', domain: 'prestigesubaru.com' },
  ]),
  ...rows('Mazda', [
    { name: 'Mazda of Englewood', city: 'Englewood', domain: 'mazdaofenglewood.com' },
    { name: 'Mazda of Turnersville', city: 'Turnersville', domain: 'mazdaturnersville.com' },
    { name: 'Freehold Mazda', city: 'Freehold', domain: 'freeholdmazda.com' },
    { name: 'Mazda of Atlantic City', city: 'Egg Harbor Township', domain: 'mazdaofatlanticcity.com' },
    { name: 'Route 22 Mazda', city: 'Hillside', domain: 'route22mazda.com' },
    { name: 'Hudson Mazda', city: 'Jersey City', domain: 'hudsonmazda.com' },
    { name: 'Flemington Mazda', city: 'Flemington', domain: 'flemingtonmazda.com' },
    { name: 'Mazda of Morristown', city: 'Morristown', domain: 'mazdaofmorristown.com' },
    { name: 'Cherry Hill Mazda', city: 'Cherry Hill', domain: 'cherryhillmazda.com' },
  ]),
  ...rows('Volkswagen', [
    { name: 'Volkswagen of Springfield', city: 'Springfield', domain: 'vwspringfieldnj.com' },
    { name: 'Volkswagen of Ridgefield Park', city: 'Ridgefield Park', domain: 'vwridgefieldpark.com' },
    { name: 'Volkswagen of Freehold', city: 'Freehold', domain: 'vwfreehold.com' },
    { name: 'Volkswagen of Turnersville', city: 'Turnersville', domain: 'vwturnersville.com' },
    { name: 'Hudson Volkswagen', city: 'Jersey City', domain: 'hudsonvw.com' },
    { name: 'Flemington Volkswagen', city: 'Flemington', domain: 'flemingtonvw.com' },
    { name: 'Volkswagen of Atlantic City', city: 'Egg Harbor Township', domain: 'vwatlanticcity.com' },
    { name: 'Princeton Volkswagen', city: 'Lawrenceville', domain: 'princetonvw.com' },
    { name: 'DCH Millburn Volkswagen', city: 'Maplewood', domain: 'dchmillburnvw.com' },
  ]),
  ...rows('Audi', [
    { name: 'Audi Cherry Hill', city: 'Cherry Hill', domain: 'audicherryhill.com' },
    { name: 'Audi Englewood', city: 'Englewood', domain: 'audienglewood.com' },
    { name: 'Audi Turnersville', city: 'Turnersville', domain: 'auditurnersville.com' },
    { name: 'Audi Atlantic City', city: 'Egg Harbor Township', domain: 'audiatlanticcity.com' },
    { name: 'Ray Catena Audi', city: 'Edison', domain: 'raycatenaaudi.com' },
    { name: 'Audi Flemington', city: 'Flemington', domain: 'audiflemington.com' },
    { name: 'Audi Bridgewater', city: 'Bridgewater', domain: 'audibridgewater.com' },
    { name: 'Jack Daniels Audi', city: 'Upper Saddle River', domain: 'jackdanielsaudi.com' },
    { name: 'DCH Millburn Audi', city: 'Maplewood', domain: 'dchmillburnaudi.com' },
    { name: 'Audi Princeton', city: 'Princeton', domain: 'audiprinceton.com' },
  ]),
  ...rows('BMW', [
    { name: 'BMW of Springfield', city: 'Springfield', domain: 'bmwofspringfield.com' },
    { name: 'BMW of Morristown', city: 'Morristown', domain: 'morristownbmw.com' },
    { name: 'BMW of Bloomfield', city: 'Bloomfield', domain: 'bmwofbloomfield.com' },
    { name: 'BMW of Tenafly', city: 'Tenafly', domain: 'bmwoftenafly.com' },
    { name: 'BMW of Ramsey', city: 'Ramsey', domain: 'bmwoframsey.com' },
    { name: 'Paul Miller BMW', city: 'Parsippany', domain: 'paulmillerbmw.com' },
    { name: 'BMW of Freehold', city: 'Freehold', domain: 'bmwoffreehold.com' },
    { name: 'BMW of Atlantic City', city: 'Egg Harbor Township', domain: 'bmwofatlanticcity.com' },
    { name: 'BMW of Turnersville', city: 'Turnersville', domain: 'bmwturnersville.com' },
    { name: 'Princeton BMW', city: 'Lawrenceville', domain: 'princetonbmw.com' },
    { name: 'Flemington BMW', city: 'Flemington', domain: 'flemingtonbmw.com' },
    { name: 'Circle BMW', city: 'Eatontown', domain: 'circlebmw.com' },
    { name: 'JMK BMW', city: 'Springfield', domain: 'jmkbmw.com' },
  ]),
  ...rows('Mercedes-Benz', [
    { name: 'Mercedes-Benz of Bridgewater', city: 'Bridgewater', domain: 'mercedesbenzofbridgewater.com' },
    { name: 'Mercedes-Benz of Cherry Hill', city: 'Cherry Hill', domain: 'mbcherryhill.com' },
    { name: 'Ray Catena Mercedes-Benz', city: 'Edison', domain: 'raycatenamb.com' },
    { name: 'Mercedes-Benz of Fairfield', city: 'Fairfield', domain: 'mboffairfield.com' },
    { name: 'Mercedes-Benz of Flemington', city: 'Flemington', domain: 'mbflemington.com' },
    { name: 'Mercedes-Benz of Princeton', city: 'Lawrenceville', domain: 'mbprinceton.com' },
    { name: 'Mercedes-Benz of Springfield', city: 'Springfield', domain: 'mbofspringfield.com' },
    { name: 'Mercedes-Benz of Fort Lee', city: 'Fort Lee', domain: 'mbofortlee.com' },
    { name: 'Mercedes-Benz of Atlantic City', city: 'Egg Harbor Township', domain: 'mbatlanticcity.com' },
    { name: 'Contemporary Motor Cars', city: 'Little Silver', domain: 'cmcbenz.com' },
    { name: 'Mercedes-Benz of Newton', city: 'Newton', domain: 'mbofnewton.com' },
  ]),
  ...rows('Volvo', [
    { name: 'Volvo Cars Princeton', city: 'Lawrenceville', domain: 'volvocarsprinceton.com' },
    { name: 'Volvo Cars Englewood', city: 'Englewood', domain: 'volvocarsenglewood.com' },
    { name: 'Volvo Cars Edison', city: 'Edison', domain: 'volvocarsedison.com' },
    { name: 'Volvo Cars Morristown', city: 'Morristown', domain: 'volvocarsmorristown.com' },
    { name: 'Volvo Cars Atlantic City', city: 'Egg Harbor Township', domain: 'volvocarsatlanticcity.com' },
    { name: 'Paul Miller Volvo', city: 'Parsippany', domain: 'paulmillervolvo.com' },
    { name: 'Flemington Volvo Cars', city: 'Flemington', domain: 'flemingtonvolvo.com' },
  ]),
  ...rows('Mini', [
    { name: 'MINI of Mount Laurel', city: 'Mount Laurel', domain: 'miniofmountlaurel.com' },
    { name: 'MINI of Springfield', city: 'Springfield', domain: 'miniofspringfield.com' },
    { name: 'Circle MINI', city: 'Eatontown', domain: 'circlemini.com' },
    { name: 'MINI of Flemington', city: 'Flemington', domain: 'miniflemington.com' },
    { name: 'Paul Miller MINI', city: 'Parsippany', domain: 'paulmillermini.com' },
  ]),
  ...rows('Mitsubishi', [
    { name: 'Mitsubishi of Turnersville', city: 'Turnersville', domain: 'mitsubishiturnersville.com' },
    { name: 'Freehold Mitsubishi', city: 'Freehold', domain: 'freeholdmitsubishi.com' },
    { name: 'Route 22 Mitsubishi', city: 'Hillside', domain: 'route22mitsubishi.com' },
    { name: 'Hudson Mitsubishi', city: 'Jersey City', domain: 'hudsonmitsubishi.com' },
    { name: 'Cherry Hill Mitsubishi', city: 'Cherry Hill', domain: 'cherryhillmitsubishi.com' },
  ]),
].filter((d) => d.domain && d.domain !== 'skip.invalid' && d.state === 'NJ');
