#!/usr/bin/env node
/**
 * Regenerates lib/porscheColorCodes.generated.ts from data/porsche_color_codes.csv.
 *
 *   node scripts/build_porsche_color_codes.mjs
 *
 * The CSV is the Stuttcars Porsche color database (colors.stuttcars.com,
 * pulled 2026-09-04): every factory and Paint-to-Sample color 1950–present
 * with its paint code(s). Only codes of three or more characters go into the
 * generated table — the two-character *order* codes the dealer feed actually
 * carries (e.g. "0Q0Q") live in lib/porscheColors.ts, confirmed one by one
 * against Porsche's own configurator rather than a third-party list, because
 * those short codes get reused across eras and a wrong name is worse than none.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const csvPath = join(root, "data", "porsche_color_codes.csv");
const outPath = join(root, "lib", "porscheColorCodes.generated.ts");

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') {
        field += '"';
        i++;
      } else if (ch === '"') {
        quoted = false;
      } else {
        field += ch;
      }
    } else if (ch === '"') {
      quoted = true;
    } else if (ch === ",") {
      row.push(field);
      field = "";
    } else if (ch === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (ch !== "\r") {
      field += ch;
    }
  }
  if (field || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

const [header, ...lines] = parseCsv(readFileSync(csvPath, "utf8"));
const col = (name) => header.indexOf(name);
const iCodes = col("all_codes");
const iName = col("name");
const iYears = col("years");
const iPts = col("pts_only");

// code -> candidate names. When one code names several colors (it happens —
// the Stuttcars data has M4W as both Purple Sky and Ultraviolet), prefer the
// color still on sale, then a non-PTS color, then the first seen.
const candidates = new Map();
for (const line of lines) {
  if (!line[iName]) continue;
  const name = line[iName].trim();
  const current = (line[iYears] || "").endsWith("present");
  const pts = line[iPts] === "yes";
  for (const raw of (line[iCodes] || "").split("/")) {
    const code = raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
    if (code.length < 3 || code.length > 8) continue;
    // "Special Order" / "PTS" placeholders in the source are not paint codes.
    if (["SPECIAL", "ORDER", "PTS"].includes(code)) continue;
    const list = candidates.get(code) || [];
    list.push({ name, current, pts });
    candidates.set(code, list);
  }
}

const entries = [];
const conflicts = [];
for (const [code, list] of [...candidates.entries()].sort()) {
  const names = [...new Set(list.map((c) => c.name))];
  const pick =
    list.find((c) => c.current && !c.pts) || list.find((c) => c.current) || list.find((c) => !c.pts) || list[0];
  if (names.length > 1) conflicts.push(`${code}: ${names.join(" | ")} -> ${pick.name}`);
  entries.push([code, pick.name]);
}

const out = `// GENERATED by scripts/build_porsche_color_codes.mjs from data/porsche_color_codes.csv — do not edit by hand.
// Porsche paint codes (three characters and longer) → color name, 1950–present, factory and Paint to Sample.
// Source: Stuttcars Porsche color database (colors.stuttcars.com), pulled 2026-09-04. ${entries.length} codes.

export const PORSCHE_PAINT_CODES: Record<string, string> = {
${entries.map(([code, name]) => `  ${JSON.stringify(code)}: ${JSON.stringify(name)},`).join("\n")}
};
`;
writeFileSync(outPath, out);
console.log(`wrote ${outPath}: ${entries.length} codes`);
if (conflicts.length) console.log(`resolved ${conflicts.length} code conflicts:\n  ${conflicts.join("\n  ")}`);
